# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "node#{i}.tp3.b2" do |node|
      node.vm.box = "super_box"

      node.vm.box_check_update = false

      node.vm.network "private_network", type: "dhcp"

      node.vm.network "private_network", ip: "10.3.1.1#{i}"


      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
    end
  end
end