version: "3.1"
services:
  php-apache:
    image: php:7.2-apache
    ports:
      - "80:80"
    volumes:
      - "/src/index.html:/var/www/html/"
    mem_limit: 1g
    cpus: 1

  sql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=alexandre
      - MYSQL_PASSWORD=alexandre
      - MYSQL_DATABASE=data-base
    volumes:
      - "./base.sql:/docker-entrypoint-initdb.d/init.sql"
    mem_limit: 1g
    cpus: 1

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: sql
      PMA_PORT: 3306
    mem_limit: 1g
    cpus: 1

  nginx:
    image: nginx



networks:
  mon-networks: 
    driver: bridge